In [8]:
# build computing graph of tensorflow

import tensorflow as tf

tf_c = tf.constant(2, name='const')
tf_x = tf.Variable(tf_c+5, name='tf_x')

width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)

# executing
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('tf_c: ', sess.run(tf_c))
    print('tf_x: ',sess.run(tf_x))
    print('eval of tf_x: ', tf_x.eval(session=sess))
    
    print('area: ', sess.run(area, feed_dict={width: 5, height: 3}))


tf_c:  2
tf_x:  7
eval of tf_x:  7
area:  15


In [9]:
# output the file for TensorBoard
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

In [17]:
# building the vector
tf_vec = tf.Variable([0.4, 0.2, 0.4])
tf_mat_a = tf.Variable([[1, 2, 3]])
tf_mat_b = tf.Variable([[1, 3, 5],
                  [2, 4, 6],
                  [9, 10, 11]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    vec = sess.run(tf_vec)
    print(vec)
    print('shape: ', vec.shape)
    
    mat_a = sess.run(tf_mat_a)
    mat_b = sess.run(tf_mat_b)
    print('mat a: ', mat_a)
    print('shape: ', mat_a.shape)
    print('mat b: ', mat_b)
    print('shape: ', mat_b.shape)
    
    

[0.4 0.2 0.4]
shape:  (3,)
mat a:  [[1 2 3]]
shape:  (1, 3)
mat b:  [[ 1  3  5]
 [ 2  4  6]
 [ 9 10 11]]
shape:  (3, 3)
